package com.example.budgettrackerapp.data

import androidx.room.Entity
import androidx.room.PrimaryKey

// Declares the 'users' table for Room persistence
@Entity(tableName = "users")
data class User(

    // Primary key for the user table; auto-generated by Room
    @PrimaryKey(autoGenerate = true) val userId: Int = 0,

    // Username used for login; should be unique
    val username: String,

    // Hashed password stored securely
    val password: String,

    // Optional profile picture stored as a byte array (e.g., for avatar image)
    val profilePicture: ByteArray? = null
)
